default-target = "wasm32-unknown-emscripten"

[cargo-web]
minimum-version = "0.6.0"

[target.emscripten]
link-args = [
  "-s",
  "USE_SDL=2",
  "-s",
  "MIN_WEBGL_VERSION=2",
  "-s",
  "MAX_WEBGL_VERSION=2",
  "--embed-file",
  "title.txt",
]
